<?php
/**
 * Offline stores catalog template
 *
 * @see Webinse_OfflineStores_Block_Widget_Offlinestore
 */
?>
<?php
$_helper    = $this->helper('webinseofflinestores/output');
$_offlineStoreCollection  = $this->getLoadedOfflineStoreCollection();
?>

<?php if(!$_offlineStoreCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no offline stores matching the selection.') ?></p>
<?php else: ?>
    <div class="offlinestore-section">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if($this->getMode()!='1'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_offlineStoreCollection as $_offlineStore): ?>
                    <li class="item<?php if( ++$_iterator == sizeof($_offlineStoreCollection) ): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo $_offlineStore->getOfflineStoreUrl() ?>" title="<?php echo $this->stripTags($this->getName(), null, true) ?>" class="product-image">

                            <?php $_imgSize = 300; ?>
                            <?php // $this->helper('webinseofflinestores/image')->init($_offlineStore, 'small_image'); die('?'); ?>
                            <img id="product-collection-image-<?php echo $_offlineStore->getId(); ?>"
                                 src="<?php echo $_offlineStore->getImageUrl(); ?>"
                                 alt="" />
                        </a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <div class="product-primary">
                                    <?php $_offlineStoreNameStripped = $this->stripTags($_offlineStore->getName(), null, true); ?>
                                    <h2 class="product-name"><a href="<?php echo $_offlineStore->getOfflineStoreUrl() ?>" title="<?php echo $_offlineStoreNameStripped; ?>"><?php echo $_offlineStoreNameStripped; ?></a></h2>
                                </div>
                                <div class="desc std">
                                    <?php echo $_helper->offlineStoreAttribute($_offlineStore, $_offlineStore->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_offlineStore->getOfflineStoreUrl() ?>" title="<?php echo $_offlineStoreNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

        <?php // Grid Mode ?>

        <?php $_collectionSize = $_offlineStoreCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
            <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
                <?php $i=0; foreach ($_offlineStoreCollection as $_offlineStore): ?>
                    <?php /*if ($i++%$_columnCount==0): ?>
            <?php endif*/ ?>
                    <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                        <a href="<?php echo $_offlineStore->getOfflineStoreUrl() ?>" title="<?php echo $_offlineStore->getImageUrl() ?>" class="product-image">
                            <?php $_imgSize = 210; ?>
                            <img id="product-collection-image-<?php echo $_offlineStore->getId(); ?>"
                                 src="<?php echo $_offlineStore->getImageUrl();//->resize($_imgSize) ?>"
                                 alt="<?php echo $this->stripTags($_offlineStore->getName()) ?>" />
                        </a>
                        <div class="product-info">
                            <h2 class="product-name"><a href="<?php echo $_offlineStore->getOfflineStoreUrl() ?>" title="<?php echo $this->stripTags($_offlineStore->getName(), null, true) ?>"></a></h2>
                            <?php // echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        </div>
                    </li>
                    <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif*/ ?>
                <?php endforeach ?>
            </ul>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php endif; ?>

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>
<?php die('end'); ?>


<?
$_imgHtml   = '';
if ($_imgUrl = $_category->getImageUrl()) {
    $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
    $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
}
?>
<div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php if($_imgUrl): ?>
    <?php echo $_imgHtml ?>
<?php endif; ?>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
<?php endif; ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
