<?php
/**
 * Created by PhpStorm.
 * User: forint
 * Date: 4/6/16
 * Time: 3:17 PM
 */
class DS_News_Model_Resource_News_Collection extends Mage_Core_Model_Mysql4_Collection_Abstract {

    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('dsnews/news');
    }

}