<?php
/**
 * Created by PhpStorm.
 * User: forint
 * Date: 4/6/16
 * Time: 5:02 PM
 */
class DS_News_Block_Adminhtml_News_Grid extends Mage_Adminhtml_Block_Widget_Grid {

    protected function _prepareCollection()
    {

        $collection = Mage::getModel('dsnews/news')->getCollection();
        $this->setCollection($collection);

        return parent::_prepareCollection();
    }

    protected function _prepareColumns()
    {
        $helper = Mage::helper('dsnews');

        $this->addColumn('news_id', array(
            'header' => $helper->__('News ID'),
            'index'  => 'news_id',
            'width'  => '30px'
        ));

        $this->addColumn('title', array(
            'header' => $helper->__('Title'),
            'index' => 'title',
            'type' => 'text',
        ));

        $this->addColumn('category', array(
            'header' => $helper->__('Category'),
            'index' => 'category_id',
            'options' => $helper->getCategoriesList(),
            'type'  => 'options',
            'width' => '70px',
        ));

        $this->addColumn('created', array(
            'header' => $helper->__('Created'),
            'index'  => 'created',
            'type'   => 'date',
            'width'  => '80px'
        ));

        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }

    protected function _prepareMassaction()
    {
        // Устанавливаем id-поле
        $this->setMassactionIdField('news_id');
        // Устанавливаем название параметра, которое будет использоваться для получения массива id-полей
        $this->getMassactionBlock()->setFormFieldName('news');

        // Добавляем опции в список масовых операций
        // id операции, название и ссылка, куда отправлять выбранные записи
        $this->getMassactionBlock()->addItem('delete', array(
            'label' => $this->__('Delete'),
            'url'   => $this->getUrl('*/*/massDelete'),
        ));
        return $this;
    }

    /*
     * Method to initiliaze reference for each row of Data Grid
     * Response to the user clicking on a line
     */
    public function getRowUrl($model){

        return $this->getUrl('*/*/edit', array(
            'id' => $model->getId(),
        ));

    }
}