<?php
/**
 * Created by PhpStorm.
 * User: forint
 * Date: 4/6/16
 * Time: 3:12 PM
 */
class DS_News_Model_News extends Mage_Core_Model_Abstract {

    private $_newsEventName = 'news_event';

    public function _construct(){
        parent::_construct();
        $this->_init('dsnews/news');

        /**
         * Add event after load module News
         */
        $this->addObserverCustomEvent();
    }

    protected function _afterDelete()
    {
        $helper = Mage::helper('dsnews');
        @unlink($helper->getImagePath($this->getId()));
        return parent::_afterDelete(); // TODO: Change the autogenerated stub
    }

    public function getImageUrl(){

        $helper = Mage::helper('dsnews');
        if ($this->getId() && file_exists($helper->getImagePath($this->getId()))){
            return $helper->getImageUrl($this->getId());
        }
        return null;
    }

    protected function _beforeSave(){

        $helper = Mage::helper('dsnews');

        if (!$this->getData('link')){
            $this->setData('link', $helper->prepareUrl($this->getTitle()));
        }else{
            $this->setData('link', $helper->prepareUrl($this->getData('link')));
        }
        return parent::_beforeSave();
    }

    private function dispatchCustomEvent(){

        $event_data_array = array(
            'cid'=>'123'
        );

        $varien_object = new Varien_Object($event_data_array);
        Mage::dispatchEvent('my_custom_event', array('varien_obj'=>$varien_object));

        echo $varien_object->getCid();
    }

    public function addObserverCustomEvent(){

        // create event's and observer's objects
        $event = new Varien_event();
        $event->setName($this->_newsEventName);
        $observer = new Varien_Event_Observer();

        // assign event to observer
        $observer->setData(array('event'=>$event));

    }
}