<?php
$nav = array(
    '/' => 'Home',
    'news' => 'News',
    'maryjanefashion' => 'Fashion'
);
$uri = $this->getRequest()->getRequestUri();
$res = explode('/',$uri);
$uri = $res[1];

?>
<div class="row left-nav-menu">
    <div class="col-sm-12">
        <div class="sidebar-nav">
            <div class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <span class="visible-xs navbar-brand">Sidebar menu</span>
                </div>
                <div class="navbar-collapse collapse sidebar-navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php foreach ($nav as $url=>$title): ?>
                            <li <?php echo $active = ($uri == $url)?'class="active"':''; ?>><a href="<?php echo ($url == '/')?'':'/';echo $url; echo ($url == '/')?'':'/'; ?>" title="<?php echo $title; ?>"><?php echo $title; ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>
</div>