<script type="text/javascript">
function saveAndContinueEdit(urlTemplate) {
        var template = new Template(urlTemplate, /(^|.|\r|\n)({{(\w+)}})/);
        var url = template.evaluate({tab_id: offlinestores_info_tabsJsTabs.activeTab.id});
        editForm.submit(url);
}
editForm._processValidationResult = function(transport) {
        var response = transport.responseText.evalJSON();
        if (response.error) {
                if (response.attribute && $(response.attribute)) {
                        $(response.attribute).setHasError(true, offlineStoreForm);
                        Validation.ajaxError($(response.attribute), response.message);
                        if (!Prototype.Browser.IE) {
                                $(response.attribute).focus();
                        }
                }
                else if ($('messages')) {
                        $('messages').innerHTML = '<ul class="messages"><li class="error-msg"><ul><li>' + response.message + '</li></ul></li></ul>';
                }
        }
        else {
            editForm._submit();
        }
}
</script>
